spring.application.name=demo

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@172.27.129.116:1521/MOLAP
spring.datasource.username=rsatylganov
spring.datasource.password=1q@W3e$R
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# import excel
excel.import-dir=import/in
excel.archive-dir=import/out
excel.file-name=import_from_excel.xlsx
excel.table-name=import_from_excel
excel.db-column-id=ID
excel.db-column-code=CODE
excel.db-column-name=NAME
excel.column-code=1
excel.column-name=2
